### ISSUE TITLE
DPV v2 Release Issue Tracker

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#127]
## Issues fixed in code

- [x] dpv: Add Legal/Physical measure to TOM
- [x] dpv: Data module page is missing
- [x] dpv_legal_basis: Missing concepts for terms defined in main vocabulary e.g. dpv:Context
- [x] dpv: Resolve duplicate contributors
- [x] dpv: Resolve multiple contributors in term definition e.g. isImplementedByEntity
- [x] dpv: Resolve multiple creation dates in term definition e.g. isImplementedByEntity
- [x] dpv: Update Automation and Human Involvement concepts
- [x] legal_eu_rights: WARNING: Unstable concepts
- [x] legal_eu_dga: parent missing SIP - should be SingleInformationPoint
- [x] pd: express existence and relations to other vocabularies
- [x] primer: Fix broken links e.g. DPV-PD
- [x] primer: fix broken image links from img -> media
- [x] rights: Add descriptions, rights exercise section
- [x] risk: parent missing e.g. EBIOS ->    risk:RiskManagement
- [x] risk: parent missing e.g. EnvironmentalSafetyEndangerment -> dpv:Harm has wrong local href
- [x] risk: Add Risk Management concepts" data-number="74
- [x] risk: WARNING: unstable vocabulary
- [x] tech: Fix incorrect parents e.g. BluetoothCommunication -> NetworkingCommunication
- [x] tech: Fix missing concept e.g. LocalStorage does not exist
- [x] tech: Fix missing concepts e.g. GPS -> GPSCommunication

## Review content

- [x] dpv
- [x] dpv_context
- [x] dpv_entities
- [x] dpv_legal_basis
- [x] dpv_processing
- [x] dpv_purposes
- [x] dpv Review and update section descriptions
- [x] dpv_rights
- [x] dpv_risk
- [x] dpv_rules
- [x] dpv_TOM
- [x] legal_eu_gdpr
- [x] primer
- [x] tech

## Add content

- [x] dpv: Statement on changes in v2
- [x] dpv_entities: Children
- [x] dpv_entities: Consumer Roles
- [x] dpv_entities: Data Controller
- [x] dpv_entities: Data Importer/Exporter
- [x] dpv_entities: Data Processor
- [x] dpv_entities: Data Recipient
- [x] dpv_entities: Data Subject
- [x] dpv_entities: DPA
- [x] dpv_entities: DPO
- [x] dpv_entities: Organisation
- [x] dpv_entities: Public Roles
- [x] dpv_entities: Third Party
- [x] dpv_entities: Vulnerable Data Subjects
- [x] dpv_legal_basis: Consent Status
- [x] dpv_legal_basis: Consent Types
- [x] dpv_legal_basis: Consent usage and examples
- [x] dpv_legal_basis: Contract
- [x] dpv_legal_basis: Legal Obligation
- [x] dpv_legal_basis: Legitimate Interest
- [x] dpv_legal_basis: Link to ISO 27560
- [x] dpv_legal_basis: Official Authority
- [x] dpv_legal_basis: Protecting Vital Interest
- [x] dpv_legal_basis: Public Interest
- [x] dpv_processing: Automation and Human Involvement
- [x] dpv_processing: Data Source
- [x] dpv_processing: Decision Making
- [x] dpv_processing: Innovative Use
- [x] dpv_processing: Processing operations
- [x] dpv_processing: Processing Scale
- [x] dpv_processing: Storage Conditions
- [x] dpv_purposes: Communication
- [x] dpv_purposes: Guidelines on Purposes
- [x] dpv_purposes: Legal Obligation/Compliance
- [x] dpv_purposes: Maintaining Security
- [x] dpv_purposes: Marketing
- [x] dpv_purposes: Organisational Governance
- [x] dpv_purposes: Personalisation
- [x] dpv_purposes: Sector of Operation
- [x] dpv_purposes: Service Provision
- [x] dpv_rights: Rights Exercise
- [x] dpv_rights: Rights Notices
- [x] dpv_rights: Rights Records
- [x] dpv_risk: Consequence &amp; Impact
- [x] dpv_risk: Further Risk Modeling
- [x] dpv_risk: Risk
- [x] dpv_risk: Risk Mitigation
- [x] dpv_rules: Further Rules Modeling
- [x] dpv_rules: Obligation
- [x] dpv_rules: Permission
- [x] dpv_rules: Prohibition
- [x] dpv_TOM: Access Control
- [x] dpv_TOM: Assessments
- [x] dpv_TOM: Authentication
- [x] dpv_TOM: Consultations
- [x] dpv_TOM: Cryptographic Methods
- [x] dpv_TOM: Data Backup
- [x] dpv_TOM: Encryption
- [x] dpv_TOM: Governance Procedures
- [x] dpv_TOM: Guidelines/Codes of Conduct
- [x] dpv_TOM: Legal Agreements/Contracts
- [x] dpv_TOM: Legal Measures
- [x] dpv_TOM: Notices
- [x] dpv_TOM: Physical Measures
- [x] dpv_TOM: Policies
- [x] dpv_TOM: Record Keeping
- [x] dpv_TOM: Sanitisation/Anonymisation
- [x] dpv_TOM: Security
- [x] dpv_TOM: Security Procedures
- [x] dpv_TOM: Staff Training
- [x] legal_eu_dga: Entities
- [x] legal_eu_dga: Introduction
- [x] legal_eu_dga: Legal Bases
- [x] legal_eu_dga: Registers
- [x] legal_eu_dga: Services
- [x] legal_eu_dga: Tech/Org Measures
- [x] locations: Overview
- [x] locations: Subdivisions
- [x] pd: Core taxonomy
- [x] pd: External
- [x] pd: Financial
- [x] pd: Historical
- [x] pd: Internal
- [x] pd: Social
- [x] pd: Special Categories
- [x] pd: Tracking
- [x] risk: Consequences and Impacts
- [x] risk: Risk Assessment Techniques
- [x] risk: Risk Controls
- [x] risk: Risk, Likelihood, Severity Levels
- [x] risk: RiskMatrix
- [x] risk: Risk Methodology
- [x] tech: Actors
- [x] tech: Communication Methods
- [x] tech: Core Concepts
- [x] tech: Data Tech
- [x] tech: Operational Tech
- [x] tech: Provision Method
- [x] tech: Security Tech
- [x] tech: Surveillance Types
- [x] tech: Tools

## w3id update

Track PR to w3id at https://github.com/perma-id/w3id.org/pull/3958

**Comment by besteves4** [comment]
@coolharsh55 are you aware that the first bit of text at the start of each spec HTML document still has the old namespaces?

E.g. in the GDPR extension it says "DPV-GDPR extends the [Data Privacy Vocabulary (DPV) Specification](https://w3id.org/dpv) to provide taxonomies of concepts such as legal bases, rights, and data transfer tools as defined within the [General Data Protection Regulation (GDPR)](https://eur-lex.europa.eu/eli/reg/2016/679/oj).

The canonical URL for DPV-GDPR is https://w3id.org/dpv/dpv-gdpr which contains (this) specification. The namespace for DPV terms is https://w3id.org/dpv/dpv-gdpr#, the suggested prefix is dpv-gdpr, and this document along with source and releases are available at https://github.com/w3c/dpv."

**Comment by coolharsh55** [comment]
Hi - thanks for catching that. I'll try to review these over the weekend. Also the w3id links are broken :/ So also fixing that.

**Comment by coolharsh55** [comment]
Closing this issue as all documentation has been completed. For diagrams, use https://github.com/w3c/dpv/issues/166 and for w3id, use #133
