### ISSUE TITLE
DPV v1.0 release candiate - feedback, discussions, and actions

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#50]
This issue is a placeholder, and collective single representation of the feedback, discussions, and actions related to DPV v0.8.1 and its role as a release candidate for DPV 1.0.

(pinned edit) As per the [last meeting on 19 OCT](https://www.w3.org/2022/10/19-dpvcg-minutes.html), the release date is set to (approx.) 15 NOV. The below are the list of tasks/issues to be addressed by then:

- [x] DPV-Legal - remove duplicate concepts, move to EU vocabs, add pending concepts ;  
  - [x] #61 - not fixed in v1
  - [x] #48 - not fixed in v1
  - [x] #46 - note added to this effect
- [x] OWL - correctness of syntax ; 
  - [x] #59
  - [x] #42
- [x] Concepts
  - [x] Technical Measures #23
  - [x] Purpose #22
  - [x] Consent #21
  - [x] Rules #18
  - [x] Data Collection Method #16
  - [x] Personal Data and PII #14
  - [x] Sensitivity of Data #11 - not fixed in v1
  - [x] Data Subject category #5
- [x] Minor fixes
  - [x] #58 
  - [x] #15 Anonymisation methods
  - [x] #72
  - [x] #70
- [x] Release prep/docs
  - [x] #40
  - [x] #39
  - [x] #38 
  - [x] #24 - not completed in v1
  - [x] #12
  - [x] #65
  - [x] #66 - can be done after v1 publication
  - [x] #67 - can be done after v1 publication
  - [x] #68 - can be done after v1 publication
  - [x] #71 - to detect errors in concepts
- [x] Notes on Future Work
  - [x] #4 Rights Exercise - will be integrated in v1
  - [x] #64 Data Breach - not fixed in v1

**Comment by tekrajchhetri** [comment]
Figure 25 (https://w3c.github.io/dpv/primer/), EncryptionInRest and EncryptionInTransfer is confusing. What does EncryptionInRest represent? Is it TLS level encryption? I believe by EncryptionInTransfer, you mean the data encryption before transfer or?

**Comment by coolharsh55** [comment]
"At Rest" refers to data being encrypted where it 'stays' or is stored. The other one, "In Transit", relates to encrypting when data 'moves' or is transferred. I don't remember how we ended up with the form "in rest/transfer", but I do remember selecting  'Transfer' instead of 'Transit' as it aligns better with transfer as the processing verb instead of transit which is not present in DPV. The term definitions in the spec do clarfify this, e.g. https://w3id.org/dpv#EncryptionInRest.
